In [2]:
import os
import pandas as pd
from pathlib import Path

In [3]:
root = Path(os.getcwd()).parent.parent

#Change for each one of where your data is. For me in Dataset I have all the three folders
parent_directory = os.path.dirname(root)
dataset_path = os.path.join(root,'Dataset')

ADVOCATE = "advocate"
RATEBEER = "ratebeer"
MATCHED = "matched"

ADVOCATE_PATH = os.path.join(dataset_path,ADVOCATE)
RATEBEER_PATH = os.path.join(dataset_path,RATEBEER)
MATCHED_PATH = os.path.join(dataset_path,MATCHED)

Giving time needed to load data of ratings:
- ratings advocate: 3min11 -> 2.9 Go
- ratings matched: 1.1s -> 26 Mo
- ratings ratebeer: 3min 44 -> 2.8 Go

In [4]:
ratings_advocate = pd.read_csv(os.path.join(ADVOCATE_PATH,'ratings-advocate.csv'))

In [ ]:
ratings_matched = pd.read_csv(os.path.join(MATCHED_PATH,'ratings.csv'), header=1)#low mememory = False ou specify dtype

In [8]:
ratings_ratebeer = pd.read_csv(os.path.join(RATEBEER_PATH,'ratings.csv'))

Now let's look at all the columns present in the three datasets and try to sort them for our needs.

In [10]:
ratings_advocate.sample(5)

,beer_name,beer_id,brewery_name,brewery_id,style,abv,date,user_name,user_id,appearance,aroma,palate,taste,overall,rating,text,review
5958374,Alaskan Amber,1309,Alaskan Brewing Co.,429,Altbier,5.3,1353409200,andrewkgray91,andrewkgray91.704203,NaN,NaN,NaN,NaN,NaN,4.00,NaN,False
2960259,Samuel Adams Double Agent IPL,88429,Boston Beer Company (Samuel Adams),35,American Pale Lager,5.0,1366020000,cjgator3,cjgator3.60686,4.25,4.0,4.0,4.75,4.75,4.47,12oz bottleA- Pours a golden orangish color wi...,True
1705146,Parabola,41815,Firestone Walker Brewing Co.,2210,Russian Imperial Stout,14.0,1339495200,Bobbak,bobbak.680660,NaN,NaN,NaN,NaN,NaN,4.00,NaN,False
6392476,Edmund Fitzgerald Porter,226,Great Lakes Brewing Co.,73,American Porter,6.0,1354100400,ironwill54,ironwill54.705299,NaN,NaN,NaN,NaN,NaN,4.75,NaN,False
6988660,Special Herbs (Seasonal),98032,Upright Brewing Company,19866,Scottish Gruit / Ancient Herbed Ale,5.7,1393930800,eggs,eggs.578172,NaN,NaN,NaN,NaN,NaN,4.50,NaN,False

In [11]:
ratings_ratebeer.sample(5)

,beer_name,beer_id,brewery_name,brewery_id,style,abv,date,user_name,user_id,appearance,aroma,palate,taste,overall,rating,text
4923671,Rising Tide Cutter,466828,Rising Tide Brewing Company,12103,Imperial IPA,8.70,1425207600,PhatB420,15092,4,9,4,9,17,4.3,12oz bought at the brewery into a rising tide ...
4349002,Sweetwater Tavern Kokopelli India Pale Ale,3777,Sweetwater Tavern &#40;Great American Restaura...,646,India Pale Ale (IPA),5.25,1088330400,guzzler67,6979,4,6,4,8,15,3.7,"Hazy, copper appearance with a fruity aroma of..."
4209665,Weyerbacher Insanity,39419,Weyerbacher Brewing Co.,241,Barley Wine,11.10,1115546400,ancherrera,1108,4,6,4,7,17,3.8,I thought Liquor right away. Sweet and defini...
6869978,Tilquin Assemblage/Blend,178935,Gueuzerie Tilquin,12859,Lambic Style - Gueuze,6.40,1413799200,Alengrin,325955,3,8,2,8,17,3.8,"A so-called âluierikâ, basically a failed ..."
2869310,Alpine Beer Company Singled Out - Mosaic,403344,Alpine Beer Company &#40;CA&#41;,2776,India Pale Ale (IPA),6.00,1483441200,BeerandBlues2,9357,3,7,3,7,14,3.4,Draught at the brewery. Pours clear orange wit...

In [13]:
ratings_matched.columns

Index(['abv', 'appearance', 'aroma', 'beer_id', 'beer_name', 'brewery_id',
       'brewery_name', 'date', 'overall', 'palate', 'rating', 'review',
       'style', 'taste', 'text', 'user_id', 'user_name', 'abv.1',
       'appearance.1', 'aroma.1', 'beer_id.1', 'beer_name.1', 'brewery_id.1',
       'brewery_name.1', 'date.1', 'overall.1', 'palate.1', 'rating.1',
       'style.1', 'taste.1', 'text.1', 'user_id.1', 'user_name.1'],
      dtype='object')

| Attribute| Advocate | Matched  | Ratebeer | Present in 3| Interest |
|----------|----------|----------|----------|----------|----------|
| style    |    yes   |    yesx2      |    yes      |    yes      |    maybe      |
| abv      |    yes   |    yesx2      |   yes       |    yes      |    no      |
| date    |    yes   |     yesx2     |    yes      |    yes      |    no      |
| appearance    |    yes      |    yesx2      |     yes     |    yes      |     yes     |
| aroma    |    yes      |    yesx2      |   yes       |   yes       |    yes      |
| palate    |    yes      |    yesx2      |     yes     |    yes      |   yes       |
| taste    |    yes      |    yesx2      |    yes      |    yes      |   yes       |
| overall    |   yes       |   yesx2       |   yes       |   yes       |    yes      |
| rating    |    yes      |    yesx2      |   yes       |    yes      |    yes      |
| text   |    yes      |    yesx2      |    yes      |    yes      |    yes      |
| review   |    yes      |     yes     |    no      |    no      |    no      |



In this table we do not care about the beer/user/brewery name/id etc...
Advocate and ratebeer dataset provide us with a review dataset which contains only the text. Furthermore advocate_ba and rb contain also the same attributes.

Now let's look at which column can contain nan values.